### ISSUE TITLE
consider `niworkflows.nipype` -> `nipype`

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/niworkflows#183] opened 2017-07-06 17:49 UTC
for a variety of reasons ;)
if you want to hardcode to specific nipype version/repo(clone) -- use git submodules mechanism (but again -- better outside of the `niworkflows/`)

**Comment by effigies** [comment] 2017-07-06 18:04
We are using submodules. What modification in approach are you suggesting?

See poldracklab/fmriprep#541 and #174 for the discussions that led to this state of affairs. The short story is: we need new versions of nipype on a shorter release cycle than nipype can handle, which causes problems for users who install fmriprep or MRIQC through pip.

**Comment by effigies** [comment] 2017-07-06 19:16
Really? You can't use fmriprep when installed locally? In our experience, this resolved the issue with users installing through pip. What specifically happens when you try?

I'm open to migrating back, if it can be made to work, but in our experience placing git commit references in the `requirements.txt` did not result in the pinned commit being installed. I believe this may have been because of the issue you reference in the linked commit, which is that `requirements.txt` is only read for `-e` installs. Which we can't support because that breaks Singularity images.

Finally, it may be that users want to have a stable version of nipype installed. If we did successfully pin to commits, we would be replacing that. I suppose this could be managed by virtual environments, but given that this is done to accommodate people who can't/won't run Docker, I'm not sure we can expect them to maintain a virtual environment just for fmriprep.

**Comment by yarikoptic** [comment] 2017-07-06 19:27
sorry -- I meant "pip install" niworkflows:
```shell
$> virtualenv --system-site-packages --python=python venv-niwork
Running virtualenv with interpreter /usr/bin/python             
New python executable in /tmp/venv-niwork/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$> source venv-niwork/bin/activate

$> pip install https://github.com/poldracklab/niworkflows/archive/master.zip
Collecting https://github.com/poldracklab/niworkflows/archive/master.zip
  Downloading https://github.com/poldracklab/niworkflows/archive/master.zip
     / 1.8MB 86.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-k05VyU-build/setup.py", line 49, in <module>
        main()
      File "/tmp/pip-k05VyU-build/setup.py", line 18, in main
        'niworkflows', 'info.py'))
      File "/usr/lib/python2.7/runpy.py", line 252, in run_path
        return _run_module_code(code, init_globals, run_name, path_name)
      File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/pip-k05VyU-build/niworkflows/info.py", line 17, in <module>
        'nipype', 'info.py'))
      File "/usr/lib/python2.7/runpy.py", line 251, in run_path
        code = _get_code_from_file(path_name)
      File "/usr/lib/python2.7/runpy.py", line 227, in _get_code_from_file
        with open(fname, "rb") as f:
    IOError: [Errno 20] Not a directory: '/tmp/pip-k05VyU-build/niworkflows/nipype/info.py'

```
or (uff... takes long time for some reason)
```shell
$> pip install git+https://github.com/poldracklab/niworkflows/                  
Collecting git+https://github.com/poldracklab/niworkflows/
  Cloning https://github.com/poldracklab/niworkflows/ to ./pip-UTMN8J-build
Requirement already satisfied: simplejson>=3.8.0 in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: funcsigs in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: pydotplus in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: nibabel>=2.1.0 in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: networkx>=1.9 in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Collecting packaging (from niworkflows==0.1.4.dev0)
  Using cached packaging-16.8-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.8.2 in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: configparser in /usr/lib/python2.7/dist-packages (from niworkflows==0.1.4.dev0)
....
    copying niworkflows/nipype/pipeline/engine/base.py -> build/lib.linux-x86_64-2.7/niworkflows/nipype/pipeline/engine
    running egg_info
    creating niworkflows.egg-info
    writing requirements to niworkflows.egg-info/requires.txt
    writing niworkflows.egg-info/PKG-INFO
    writing top-level names to niworkflows.egg-info/top_level.txt
    writing dependency_links to niworkflows.egg-info/dependency_links.txt
    writing manifest file 'niworkflows.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'niworkflows.egg-info/SOURCES.txt'
    error: can't copy 'niworkflows/nipype': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/tmp/venv-niwork/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-UTMN8J-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /home/yoh/.tmp/pip-N0h_QE-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv-niwork/include/site/python2.7/niworkflows" failed with error code 1 in /tmp/pip-UTMN8J-build/
pip install git+https://github.com/poldracklab/niworkflows/  16.93s user 4.00s system 31% cpu 1:06.77 total

```

**Comment by yarikoptic** [comment] 2017-07-06 19:31
but ideally imho nipype should just release ... and indeed released versions of niworkflows should use released versions of nipype ;)
before then -- "virtualenv" or another way to bundle together niworkflows with devel state of nipype is imho the only sane way to go. 
Do you know if you have many users using niworkflows outside of docker/virtualenv?

**Comment by effigies** [comment] 2017-07-06 19:38
I don't know of any direct users of niworkflows. I only ever see support requests for fmriprep. (I assume MRIQC gets them, too.)

```Shell
$> virtualenv --system-site-packages --python=python venv-niwork
Running virtualenv with interpreter /usr/bin/python             
New python executable in /tmp/venv-niwork/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$> source venv-niwork/bin/activate

$> pip install git+https://github.com/poldracklab/niworkflows/
Requirement already satisfied: networkx>=1.9 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: scipy>=0.14 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: nibabel>=2.1.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: jinja2 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: mock in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: packaging in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: click>=6.6.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: pandas in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: python-dateutil>=2.2 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: future>=0.16.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: nilearn>=0.2.6 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: matplotlib in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: funcsigs in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: pydotplus in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: simplejson>=3.8.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: numpy>=1.8.2 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: traits>=4.6 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: sklearn in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: svgutils in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: pytest>=3.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: tinycss in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: prov>=1.5.0 in ./.anaconda3/lib/python3.5/site-packages (from niworkflows==0.1.4.dev0)
Requirement already satisfied: decorator>=3.4.0 in ./.anaconda3/lib/python3.5/site-packages (from networkx>=1.9->niworkflows==0.1.4.dev0)
Requirement already satisfied: MarkupSafe>=0.23 in ./.anaconda3/lib/python3.5/site-packages (from jinja2->niworkflows==0.1.4.dev0)
Requirement already satisfied: pbr>=0.11 in ./.anaconda3/lib/python3.5/site-packages (from mock->niworkflows==0.1.4.dev0)
Requirement already satisfied: six>=1.9 in ./.anaconda3/lib/python3.5/site-packages (from mock->niworkflows==0.1.4.dev0)
Requirement already satisfied: pyparsing in ./.anaconda3/lib/python3.5/site-packages (from packaging->niworkflows==0.1.4.dev0)
Requirement already satisfied: pytz>=2011k in ./.anaconda3/lib/python3.5/site-packages (from pandas->niworkflows==0.1.4.dev0)
Requirement already satisfied: cycler>=0.10 in ./.anaconda3/lib/python3.5/site-packages (from matplotlib->niworkflows==0.1.4.dev0)
Requirement already satisfied: scikit-learn in ./.anaconda3/lib/python3.5/site-packages (from sklearn->niworkflows==0.1.4.dev0)
Requirement already satisfied: lxml in ./.anaconda3/lib/python3.5/site-packages (from svgutils->niworkflows==0.1.4.dev0)
Requirement already satisfied: py>=1.4.33 in ./.anaconda3/lib/python3.5/site-packages (from pytest>=3.0->niworkflows==0.1.4.dev0)
Requirement already satisfied: setuptools in ./venv-niwork/lib/python3.5/site-packages (from pytest>=3.0->niworkflows==0.1.4.dev0)
Requirement already satisfied: rdflib>=4.2.1 in ./.anaconda3/lib/python3.5/site-packages (from prov>=1.5.0->niworkflows==0.1.4.dev0)
Requirement already satisfied: isodate in ./.anaconda3/lib/python3.5/site-packages (from rdflib>=4.2.1->prov>=1.5.0->niworkflows==0.1.4.dev0)
Installing collected packages: niworkflows
  Found existing installation: niworkflows 0.1.3
    Not uninstalling niworkflows at /home/cjmarkie/.anaconda3/lib/python3.5/site-packages, outside environment /home/cjmarkie/venv-niwork
  Running setup.py install for niworkflows ... done
Successfully installed niworkflows-0.1.4.dev0
```

This was with Python 3; it's possible there are Python 2 issues here...

**Comment by yarikoptic** [comment] 2017-07-06 19:43
FWIW hm, setuptools/pkg_resources seems to not handle those urls nicely when defined in setup.py `setup` call... so indeed might be incomplete solution as well... heh

re your reproduced scenario -- culprit could be
```
Installing collected packages: niworkflows
  Found existing installation: niworkflows 0.1.3
    Not uninstalling niworkflows at /home/cjmarkie/.anaconda3/lib/python3.5/site-packages, outside environment /home/cjmarkie/venv-niwork
  Running setup.py install for niworkflows ... done
Successfully installed niworkflows-0.1.4.dev0
```
ie you have already niworkflows installed so it didn't bother really installing it ;-)  I did reproduce failure in "clean" installation with python3 (not worth pasting the long one here but here is the trail
```
    reading manifest template 'MANIFEST.in'
    writing manifest file 'niworkflows.egg-info/SOURCES.txt'
    error: can't copy 'niworkflows/nipype': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/tmp/venv-niwork3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-u0x3_dhl-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /home/yoh/.tmp/pip-cfbhdkvp-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv-niwork3/include/site/python3.5/niworkflows" failed with error code 1 in /tmp/pip-u0x3_dhl-build/
```

**Comment by effigies** [comment] 2017-07-06 19:57
Ugh. Isn't virtualenv supposed to create clean environments? I have no idea how to begin to reproduce your issue except perhaps in Docker... I never did get the hang of them. I figured copying your commands would be the right way to go about it.

Can you verify the submodule is getting properly checked out? That's my best guess as to the problem. If that's something that we need to modify to make that work let me know.

----

As to reproducing in Docker, that's what we do in the fmriprep [Dockerfile](https://github.com/poldracklab/fmriprep/blob/master/Dockerfile#L151), anyway. We do install several things via `conda` prior to installing via pip, so that we don't have to compile. But that doesn't seem to be your issue.

**Comment by yarikoptic** [comment] 2017-07-06 22:48
you told it `--system-site-packages` which means to allow the ones already installed -- so try without ;)
noone (i.e. pip) would do submodule check out here for you.

in your `Dockefile` setup you  do `COPY . /root/src/fmriprep` so, if I got it right, it relies on a submodule being correctly "installed" outside.  As such IMHO it is not fully describing the state of the "affairs" ;)

**Comment by effigies** [comment] 2017-07-07 00:05
fmriprep doesn't have the submodule, niworkflows does. In that Dockerfile, niworkflows is installed from its specification in `requirements.txt`. At release we use a PyPI archived release, but it is often a reference to a specific commit.

I'll try the virtual env without `--system-site-packages`.

**Comment by effigies** [comment] 2017-07-07 14:13
Yarik, I still can't reproduce this issue. A new virtualenv installed cleanly. Also a pip install on the `continuumio/miniconda{,3}` Docker images (following a `conda install traits`, as well as `subprocess32` for the Python 2 image) worked without issue.

I don't imagine you're using a pip < 1.2, so you should be cloning submodules when you pull down from the repository.

**Comment by yarikoptic** [comment] 2017-07-07 17:32
@effigies hm... I tried in a clean Debian unstable docker and "pip install git+https://github.com/poldracklab/niworkflows/" worked out just fine... hm....

**Comment by effigies** [comment] 2017-07-07 18:26
As this looks like an environment-specific issue, I'm going to close this for now. Feel free to reopen if it needs to be addressed further.

**Closed by effigies** 2017-07-07 18:26 UTC

**Comment by yarikoptic** [comment] 2017-07-07 19:01
and looked inside pip source code -- it seems indeed unconditionally update --init submodules if .gitmodules is present... so should have worked... will check later in more detail. sorry for the noise I guess (although I still feel that submodule-way is not appropriate here but since alternatives aren't at least as good -- I shut up for now ;) )
